application: fbcloud
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt


- url: /fbcloud
  script: fbcloud.py

- url: /searchall
  script: searchall.py

- url: /searchfriends
  script: searchfriends.py

- url: /searchtwitter
  script: searchtwitter.py

- url: /.*
  static_files: fancy.html
  upload: fancy.html



#- url: /.*
#  static_files: try.html
#  upload: try.html
